on:
  push:
    branches:
      - main

name: 🚀 Deploy frontend on push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: frontend-deploy
    defaults:
      run:
        working-directory: todo-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.0"

      - name: Show vars (sanitized)
        run: |
          echo "VITE_API_URL=${{ vars.VITE_API_URL }}"
          echo "VITE_BASE_URL=${{ vars.VITE_BASE_URL }}"

      - name: Create .env.production file
        run: |
          echo "VITE_API_URL=${{ vars.VITE_API_URL }}" >> .env.production
          echo "VITE_BASE_URL=${{ vars.VITE_BASE_URL }}" >> .env.production

      - name: Check that .env.production was created
        run: ls -la && cat .env.production | sed 's/=.*/=*** (hidden)/'

      - name: Debug .env.production
        run: cat .env.production

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build -- --mode production

      - name: List build output
        run: ls -la dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: todo-frontend/dist
